# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import exemplo_pb2 as exemplo__pb2


class exampleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.unary_unary = channel.unary_unary(
        '/nameko.example/unary_unary',
        request_serializer=exemplo__pb2.ExampleRequest.SerializeToString,
        response_deserializer=exemplo__pb2.ExampleReply.FromString,
        )
    self.unary_stream = channel.unary_stream(
        '/nameko.example/unary_stream',
        request_serializer=exemplo__pb2.ExampleRequest.SerializeToString,
        response_deserializer=exemplo__pb2.ExampleReply.FromString,
        )
    self.stream_unary = channel.stream_unary(
        '/nameko.example/stream_unary',
        request_serializer=exemplo__pb2.ExampleRequest.SerializeToString,
        response_deserializer=exemplo__pb2.ExampleReply.FromString,
        )
    self.stream_stream = channel.stream_stream(
        '/nameko.example/stream_stream',
        request_serializer=exemplo__pb2.ExampleRequest.SerializeToString,
        response_deserializer=exemplo__pb2.ExampleReply.FromString,
        )


class exampleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def unary_unary(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def unary_stream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stream_unary(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stream_stream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_exampleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'unary_unary': grpc.unary_unary_rpc_method_handler(
          servicer.unary_unary,
          request_deserializer=exemplo__pb2.ExampleRequest.FromString,
          response_serializer=exemplo__pb2.ExampleReply.SerializeToString,
      ),
      'unary_stream': grpc.unary_stream_rpc_method_handler(
          servicer.unary_stream,
          request_deserializer=exemplo__pb2.ExampleRequest.FromString,
          response_serializer=exemplo__pb2.ExampleReply.SerializeToString,
      ),
      'stream_unary': grpc.stream_unary_rpc_method_handler(
          servicer.stream_unary,
          request_deserializer=exemplo__pb2.ExampleRequest.FromString,
          response_serializer=exemplo__pb2.ExampleReply.SerializeToString,
      ),
      'stream_stream': grpc.stream_stream_rpc_method_handler(
          servicer.stream_stream,
          request_deserializer=exemplo__pb2.ExampleRequest.FromString,
          response_serializer=exemplo__pb2.ExampleReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nameko.example', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
